version: "3.8"
services:
  carclubapp:
    container_name: carclubapp
    image: modarwish/carclubapp:latest
    build: .
    ports:
    - published: 5000
      target: 5000
      protocol: tcp
    environment:
      DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@carclubapp_database:3306/carclub 
      #CREATE_SCHEMA:
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
    - database
  database:
    container_name: carclubapp_database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: carclub
    ports:
    - target: 3306
      published: 3306
    volumes:
    - type: volume
      source: carclub_database_volume
      target: /var/lib/mysql
      
  nginx:
    image: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: nginx/nginx.conf
      target: /etc/nginx/nginx.conf

volumes:
  carclub_database_volume:
  