version: "3.8"
services:
  carclubapp:
  container_name: carclubapp
    image: modarwish/carclubapp:latest
    build: .
    ports:
    - published: 5000
      target: 5000
      protocol: tcp
    environment:
      DATABASE_URI: mysql+pymysql://root:{MYSQL_ROOT_PASSWORD}@carclub_database:3306/carclub
      #CREATE_SCHEMA:
      #SECRET_KEY: ${SECRET_KEY}
  database:
    container_name: carclub_database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: carclub