version: "3.8"
services:
  carclubapp:
    container_name: carclubapp #for docker-compose local testing, will get ignored by Stack during Build stage
    image: modarwish/carclubapp:latest
    build: . #Used in Build stage, will get ignored by Stack during Build stage
    deploy:
      replicas: 1
    ports:
    - published: 5000
      target: 5000
    environment:
      DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@carclub_database:3306/carclub
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
    - database

  database:
    container_name: carclub_database #For docker-compose, will get ignored by Stack during Build stage
    image: mysql:5.7
    deploy:
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: carclub
    ports:
    - target: 3306
      published: 3306
    volumes:
    - type: volume
      source: carclub_database_volume
      target: /var/lib/mysql
      
  nginx:
    image: modarwish/nginx:test
    build: ./nginx #Used in Build stage, Will get ignored by Stack during Build stage
    deploy:
      replicas: 1
    ports:
    - target: 80
      published: 80
      protocol: tcp


volumes:
  carclub_database_volume:
