pipeline {
    agent any
    environment {
        // This is created when DockerHub login credentials was added with ID= DOCKER_HUB_CREDS to the UI Jenkins server… 
        // DOCKER_HUB_CRID (=username:password), which also generates DOCKER_HUB_CRID_PSW(=password) & DOCKER_HUB_CRID_USR(=username) ->to be used in setup stage
        DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
        MYSQL_ROOT_PASSWORD = credentials("MYSQL_ROOT_PASSWORD")
        SECRET_KEY = credentials("SECRET_KEY")
        TESTING_DATABSE_URI = credentials("TESTING_DATABSE_URI")
    }
    stages {
        stage('Setup') {
            steps {
               sh "bash jenkins/setup.sh"
            }
        }

        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }

        stage('Build') {
            steps {
                sh "bash jenkins/build.sh"
            }
        }

        stage('Push') {
            steps {
                sh "bash jenkins/push.sh"
            }
        }

        stage('Deploy') {
            steps {
                sh "bash jenkins/deploy.sh"
            }
        }
    }

    post {
        always {
            junit 'junit_report.xml'
            cobertura autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'coverage.xml', conditionalCoverageTargets: '70, 0, 0', failUnhealthy: false, failUnstable: false, lineCoverageTargets: '80, 0, 0', maxNumberOfBuilds: 0, methodCoverageTargets: '80, 0, 0', onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false
        }
    }
}