pipeline {
    agent any
    environment {
        // This is created when DockerHub login credentials was added with ID= DOCKER_HUB_CREDS to the UI Jenkins server… 
        // DOCKER_HUB_CRID (=username:password), which generates DOCKER_HUB_CRID_PSW(=password) & DOCKER_HUB_CRID_USR(=username) ->to be used in setup stage
        $DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
    }
    stages {
        stage('Setup') {
            steps {
               sh "bash jenkins/setup.sh"
            }
        }
        stage('Build') {
            steps {
                sh "bash jenkins/build.sh"
            }
        }

        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
        
        stage('Push') {
            steps {
                sh "bash jenkins/push.sh"
            }
        }

        stage('Deploy') {
            steps {
                sh "bash jenkins/deploy.sh"
            }
        }
    }
}